<a href="https://colab.research.google.com/github/Amrutak2/Deep-Learning/blob/main/Q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#20MAI0027
#Creating Input matrix
import numpy as np

In [50]:
values = ([1,3],[4,6],[7,9])
print("Training input values without Bias\n", values)

Training input values without Bias
 ([1, 3], [4, 6], [7, 9])


In [51]:
test2 = [[-1]] * len(values)
values = np.concatenate((test2, values), axis = 1)  
print("Training input values with bias in it\n",values)

Training input values with bias in it
 [[-1  1  3]
 [-1  4  6]
 [-1  7  9]]


In [52]:
m=3     #number of elements in each row of inputs
n=1 
wt = np.random.rand(m,n)*0.1 - 0.5
print("Initial random weights\n",wt)

Initial random weights
 [[-0.44693041]
 [-0.47035925]
 [-0.41672773]]


In [53]:
#Matrix
final = ([0],[1],[1])
print("Training data target values are\n", final)

Training data target values are
 ([0], [1], [1])


In [54]:
#updating weights
def updateWt(wt, inputs, activation, targets):
    eta = 0.25
    wt += eta*np.dot(np.transpose(inputs), targets - activation)
    return wt

In [55]:
def  predict (inputs, wt, targets):
    #representing Activation function with 'ack [[]]' variable
    ack = [[0]] * len(inputs)
    for i in range(0, len(inputs)):    
        for j in range(0,len(wt)):
            ack[i] += inputs[i][j] * wt[j]
        ack[i] = np.where(ack[i]>0, 1, 0)
        #checking values with target
        if(targets[i] != ack[i]):
            wt = updateWt(wt, inputs, ack[i], targets)
        print(ack[i])
    return wt

In [56]:
#Training our model and extracting stable weights
iterations = 5
for temp in range(0, iterations):
    print("\nIteration ",temp+1,"\n")
    wt = predict(values, wt, final)
    
print("\nTrained Weights\n", wt)


Iteration  1 

[0]
[0]
[1]

Iteration  2 

[1]
[1]
[1]

Iteration  3 

[1]
[1]
[1]

Iteration  4 

[1]
[1]
[1]

Iteration  5 

[1]
[1]
[1]

Trained Weights
 [[0.05306959]
 [1.27964075]
 [0.33327227]]


In [57]:
def perceptronPredict(wt, newInput):
    ac = np.dot(newInput, wt)
    ac = np.where(ac>0, 1, 0)
    print(ac)


newInput = ([-1.0, 7, 8])
perceptronPredict(wt, newInput)

[1]
